export enum ClothesStatus {
  WAITING_PUBLICATION = 0,
  PUBLISHED = 1,
  WAITING_ADJUSTMENT = 2,
  DELETED_BY_USER = 3,
  EXPIRED = 4,
  RESERVED = 5,
  NEGOTIATING_SELL = 6,
  SOLD = 8,
  ANALYSIS_REPROVED = 10,
  PAUSED_BY_USER = 11,
}
